# Generated by Django 2.1.3 on 2019-01-07 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='color',
            field=models.CharField(max_length=255, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='flower_name',
            field=models.CharField(max_length=90, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='img',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flowers',
            field=models.ManyToManyField(through='main_app.OrderDetail', to='main_app.Flower', verbose_name='Цветы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(null=True, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Flower', verbose_name='Цветок'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
    ]
